### ISSUE TITLE
Reduce amount of host mounts

### ISSUE THREAD

**Issue by rlex** [parca-dev/parca-agent#115]
While it's completely understandable why parca-agent requires certain mounts, it will be nice to reduce amount of host mounts in k8s.

Main point (as discussed in discord if i recall correctly) is
```yaml
- mountPath: /host/root
    name: root
    readOnly: true
```

Is mounting whole host root really needed?
