### ISSUE TITLE
Metadata association problems with children processes, part 2

### ISSUE THREAD

**Issue by mkuratczyk** [parca-dev/parca-agent#1258]
Follow up to https://github.com/parca-dev/parca-agent/issues/1157

I've tested parca-agent 0.12.0 with parca 0.15.0. Unfortunately I still see problems when trying to profile RabbitMQ containers.

This is what I see when I filter by `namespace`:
![namespace](https://user-images.githubusercontent.com/9566114/214923300-cbde58ed-81bf-49ff-8d95-2cd231be6500.png)

And this is what I see when I filter by `comm`:
![comm](https://user-images.githubusercontent.com/9566114/214923311-1d511303-d00b-4cfe-9c1d-ed6221de1697.png)

All those processes run in the `cqv2` namespace, that I filter by. It's hard to show but there are some sporadic dots on the graph when filtering by namespace.

If you want to test on your own, you should be able to deploy RabbitMQ like this:
1. deploy RabbitMQ Operator
```
kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
```
2. Deploy this manifest:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  image: rabbitmq:management
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  persistence:
    storage: 0
  rabbitmq:
    envConfig: |
      SERVER_ADDITIONAL_ERL_ARGS="+JPperf true"
```
