### ISSUE TITLE
OpenShift manifests

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#42]
Things we need added to the Kubernetes setup.

In the Parca Agent DaemonSet/container:

```yaml
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
            runAsUser: 0
```

And a `ClusterRole`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parca-agent-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
```

And a `RoleBinding`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <name>
  namespace: <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: parca-agent-scc
subjects:
- kind: ServiceAccount
  name: <name>
  namespace: <namespace>
```
