### ISSUE TITLE
[release blocker] The CPU profiler fails to load on Kubernetes after recent changes 

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#991]
#### Logs:
```
level=debug name=parca-agent ts=2022-11-03T16:27:31.404098688Z caller=cpu.go:197 msg="increased max memory locked rlimit" limit="18 EB"
libbpf: Error in bpf_create_map_xattr(stack_counts):Argument list too long(-7). Retrying without BTF.
libbpf: map 'stack_counts': failed to create: Argument list too long(-7)
libbpf: failed to load object 'parca'
```
#### Kernel version:
`Linux scw-parca-demo-default 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

#### Kernel config:
```
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPFILTER=y
CONFIG_BPFILTER_UMH=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
CONFIG_TEST_BPF=m
```

#### Daemonset config: 

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca-agent
    app.kubernetes.io/name: parca-agent
    app.kubernetes.io/version: main-5593e450
  name: parca-agent
  namespace: parca
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: observability
      app.kubernetes.io/instance: parca-agent
      app.kubernetes.io/name: parca-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: observability
        app.kubernetes.io/instance: parca-agent
        app.kubernetes.io/name: parca-agent
        app.kubernetes.io/version: main-5593e450
    spec:
      containers:
      - args:
        - /bin/parca-agent
        - --log-level=debug
        - --node=$(NODE_NAME)
        - --memlock-rlimit=0
        - --remote-store-address=parca.parca.svc.cluster.local:7070
        - --remote-store-insecure
        - --remote-store-insecure-skip-verify
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/parca-dev/parca-agent:main-5593e450
        imagePullPolicy: IfNotPresent
        name: parca-agent
        ports:
        - containerPort: 7071
          hostPort: 7071
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /run
          name: run
        - mountPath: /boot
          name: boot
          readOnly: true
        - mountPath: /proc
          name: proc
          readOnly: true
        - mountPath: /lib/modules
          name: modules
        - mountPath: /sys/kernel/debug
          name: debugfs
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - mountPath: /sys/fs/bpf
          name: bpffs
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: parca-agent
      serviceAccountName: parca-agent
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /run
          type: ""
        name: run
      - hostPath:
          path: /boot
          type: ""
        name: boot
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: cgroup
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules
      - hostPath:
          path: /sys/fs/bpf
          type: ""
        name: bpffs
      - hostPath:
          path: /sys/kernel/debug
          type: ""
        name: debugfs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

cc @javierhonduco
