### ISSUE TITLE
Allow collecting other perf-events

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#998]
When opening the perf-event, it would be nice if we could record types other than just `PERF_COUNT_SW_CPU_CLOCK`.

It might even make sense to allow passing the [event type](https://man7.org/linux/man-pages/man2/perf_event_open.2.html) itself, but a few that are interesting at first glance:

* `PERF_COUNT_HW_CACHE_ITLB`
* `PERF_COUNT_SW_PAGE_FAULTS`
* ... (pretty much anything has value, that's why they all exist)

Thanks to @tokenrove for suggesting this.

**Comment by brancz** [comment]
Thinking through the UX here. I would suggest an addition to our existing configuration file something like:

```
profilers:
- type: PERF_TYPE_SOFTWARE
  config: PERF_COUNT_SW_CPU_CLOCK
  sample: 100
  bits:
  - PerfBitDisabled
  - PerfBitFreq
```

This would describe the current profiler we have. A hardware profiler such as for iTLB cache hit/miss profiling would be another entry:

```
profilers:
- type: PERF_TYPE_SOFTWARE
  config: PERF_COUNT_SW_CPU_CLOCK
  sample: 100
  bits:
  - PerfBitDisabled
  - PerfBitFreq
- type: PERF_TYPE_HW_CACHE
  config: PERF_COUNT_HW_CACHE_ITLB
  sample: 100
  bits:
  - PerfBitDisabled
  - PerfBitFreq
```

Thougts? Or is it easy to shoot yourself in the foot with this?
